### ISSUE TITLE
C-x -C-c to quit does not work

### ISSUE THREAD

**Issue by wereket** [jcs-emacs/jcs-emacs#43]
Is this configuration evil based ?

**Comment by jcs090218** [comment]
No this is not evil based. This config is mixed of modern IDEs/editors based.

For keybindings, see [docs/keybindings.md](https://github.com/jcs-emacs/jcs-emacs/blob/master/docs/keybindings.md).

Famous evil based config, you can take a look at [doomemacs](https://github.com/doomemacs/doomemacs) or [spacemacs](https://www.spacemacs.org/).

**Comment by wereket** [comment]
in the docs/keybindings.md there is no command to completely quit emacs. I reinstalled and tried to completely quit it idid not work.
Altough no quits emacs...maybe you removed this command :) ?

**Comment by jcs090218** [comment]
The standard quit is <kbd>Alt</kbd>+<kbd>f4</kbd>; this will shutdown Emacs.

**Comment by wereket** [comment]
Thank you,
It is an awesome config,
One more question, is this considered vanilla emacs or it is a config tailored by a craftsman for craftsmen.
I mean for someone that want to learn emacs, is this configuration a pure vanilla emacs in a sense that we can follow the tutorial by executing non modified keys ?
Thank you for your time and awesome config.
Every time I say I have to stop configuring and start learning...and then I stumble on another awesome config.

**Comment by jcs090218** [comment]
> One more question, is this considered vanilla emacs or it is a config tailored by a craftsman for craftsmen.

`jcs-emacs` fits the philosophy of vanilla emacs; therefore, this config is a great example for beginners to learn. However, this config lazy loads all external config/packages (configuration for each external package) and splits them into smaller modules. So this adds a little bit of complexity.

Other configurations that are good for beginners are [centaur-emacs](https://github.com/seagle0128/.emacs.d) and [purcell's config](https://github.com/purcell/emacs.d). I don't use those since the more packages you use, the slower you get (this config has `566` packages).

> I mean for someone that want to learn emacs, is this configuration a pure vanilla emacs in a sense that we can follow the tutorial by executing non modified keys ?

Yes. `jcs-emacs` isn't like [doomemacs]() or [spacemacs](), which are heavily configured.

> Thank you for your time and awesome config.
> Every time I say I have to stop configuring and start learning...and then I stumble on another awesome config.

I'm glad you like it! 😁
